#!/usr/bin/env python3

import datetime as dt
import sys
import shutil

def compute_progress(start, end):
    # returns percentage as a decimal (0.0 - 1)
    start = dt.date.fromisoformat(start)
    end = dt.date.fromisoformat(end)
    now = dt.date.today()
    return (now - start) / (end - start)

def print_bar(columns: int, progress: float, color1: tuple, color2: tuple):
    if columns < 30:
        usable_length = columns - 6
    elif columns < 70:
        usable_length = columns - 8
    else:
        usable_length = columns - 18
    ret = ""
    ret += "|"

    r = int(color1[0])
    g = int(color1[1])
    b = int(color1[2])

    r_increment = (int(color2[0])-int(color1[0]))/usable_length
    g_increment = (int(color2[1])-int(color1[1]))/usable_length
    b_increment = (int(color2[2])-int(color1[2]))/usable_length


    for n in range(usable_length):
        r_curr = int(r + r_increment*n)
        g_curr = int(g + g_increment*n)
        b_curr = int(b + b_increment*n)
        # print(r_curr,g_curr,b_curr)
        if (n/usable_length < progress):
            ret += f"\33[38;2;{r_curr};{g_curr};{b_curr}m█\33[0m"
        else:
            ret += "-"

    ret += "| "
    if columns < 30:
        ret += f"{progress * 100:.0f}%"
    elif columns < 70:
        ret += f"{progress * 100:.1f}%"
    else:
        ret += f"{progress * 100:.2f}% Complete"
    print(ret)

def main():
    if len(sys.argv) < 3:
        print("usage: ./myfunctions.py START_DATE END_DATE [START_COLOR] [END_COLOR]")
        sys.exit(1)

    start = sys.argv[1]
    end = sys.argv[2]

    if len(sys.argv) > 3:
        color1 = tuple(sys.argv[3].split(","))
    else:
        color1 = (255,255,255)

    if len(sys.argv) > 4:
        color2 = tuple(sys.argv[4].split(","))
    else:
                                                                color2 = color1[:] # slice creates new tuple object :)

    terminal_size = shutil.get_terminal_size().columns
    if (terminal_size < 15):
        print("Terminal is too small")
        sys.exit(1)
    else:
        print_bar(terminal_size,compute_progress(start, end), color1, color2)


if __name__ == "__main__":
    main()
